function out1 = Quad2D_eom(in1)
%QUAD2D_EOM
%    OUT1 = QUAD2D_EOM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    27-Sep-2017 18:33:03

F1 = in1(7,:);
F2 = in1(8,:);
p = in1(3,:);
pd = in1(6,:);
xd = in1(4,:);
zd = in1(5,:);
t2 = F1+F2;
out1 = [xd;zd;pd;t2.*sin(p).*2.976190476190476e2;t2.*cos(p).*2.976190476190476e2-9.81e2./1.0e2;F1.*1.628714982312848e4-F2.*1.628714982312848e4];
